// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Jn8ckXKpLa18v_95jjTo19O2K-bn_PU',
    appId: '1:388737212942:web:12619f30259502540f125f',
    messagingSenderId: '388737212942',
    projectId: 'fir-project-6be91',
    authDomain: 'fir-project-6be91.firebaseapp.com',
    storageBucket: 'fir-project-6be91.firebasestorage.app',
    measurementId: 'G-0ZSZ78X530',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrEurPSXzn-X6jcy6bx7KvuNI36PYFG4',
    appId: '1:388737212942:android:48215e0c01c1f0970f125f',
    messagingSenderId: '388737212942',
    projectId: 'fir-project-6be91',
    storageBucket: 'fir-project-6be91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8rIrw2P6-dsy1bwHAwu81r_XXpuTK2bE',
    appId: '1:388737212942:ios:06d550b73e3fe35b0f125f',
    messagingSenderId: '388737212942',
    projectId: 'fir-project-6be91',
    storageBucket: 'fir-project-6be91.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.firebasequery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8rIrw2P6-dsy1bwHAwu81r_XXpuTK2bE',
    appId: '1:388737212942:ios:06d550b73e3fe35b0f125f',
    messagingSenderId: '388737212942',
    projectId: 'fir-project-6be91',
    storageBucket: 'fir-project-6be91.firebasestorage.app',
    iosBundleId: 'com.google.firebase.presents.firebasequery',
  );
}
